FROM node:18

WORKDIR /workspace

#ARG ARG_FILE
RUN mkdir /workspace/reports

RUN apt-get update && \
    apt-get install -y \
        gconf-service \
        libasound2 \
        libatk1.0-0 \
        libc6 \
        libcairo2 \
        libcups2 \
        libdbus-1-3 \
        libexpat1 \
        libfontconfig1 \
        libgcc1 \
        libgconf-2-4 \
        libgdk-pixbuf2.0-0 \
        libglib2.0-0 \
        libgtk-3-0 \
        libnspr4 \
        libpango-1.0-0 \
        libpangocairo-1.0-0 \
        libstdc++6 \
        libx11-6 \
        libx11-xcb1 \
        libxcb1 \
        libxcomposite1 \
        libxcursor1 \
        libxdamage1 \
        libxext6 \
        libxfixes3 \
        libxi6 \
        libxrandr2 \
        libxrender1 \
        libxss1 \
        libxtst6 \
        ca-certificates \
        fonts-liberation \
        libappindicator1 \
        libnss3 \
        lsb-release \
        xdg-utils \
        wget

COPY pa11y.config.json .
COPY pa11y_for_each_url.sh .
COPY analyze_urls.js .

#RUN npm init --yes
RUN npm install -g pa11y@7 --unsafe-perm=true
RUN npm install puppeteer@20 --unsafe-perm=true

ENTRYPOINT node analyze_urls.js
